stages:
  data_ingestion:
    cmd: uv run  src/CNN_Classifier/pipeline/data_ingestion_pipeline.py
    deps:
      - src/CNN_Classifier/pipeline/data_ingestion_pipeline.py
      - config.yaml
    outs:
      - artifacts/data_ingestion
  data_transformation:
    cmd: uv run  src/CNN_Classifier/pipeline/data_transformation_pipeline.py
    deps:
      - src/CNN_Classifier/pipeline/data_transformation_pipeline.py
      - config.yaml
      - artifacts/data_ingestion/balanced # Assuming the output of data ingestion is used as input for data transformation
    outs:
      - artifacts/data_transformation
  base_model_preparation:
    cmd: uv run  src/CNN_Classifier/pipeline/base_model_preparation_pipeline.py
    deps:
      - src/CNN_Classifier/pipeline/base_model_preparation_pipeline.py
      - config.yaml
    outs:
      - artifacts/base_model
  model_training:
    cmd: uv run  src/CNN_Classifier/pipeline/model_training_pipeline.py
    deps:
      - src/CNN_Classifier/pipeline/model_training_pipeline.py
      - config.yaml
      - artifacts/data_transformation
      - artifacts/base_model
    outs:
      - artifacts/model_training
  model_evaluation:
    cmd: uv run  src/CNN_Classifier/pipeline/model_evaluation_pipeline.py
    deps:
      - src/CNN_Classifier/pipeline/model_evaluation_pipeline.py
      - config.yaml
      - artifacts/model_training
      - artifacts/data_transformation
    outs:
      - artifacts/model_evaluation